"""Tests for the prek `hooks_installed.py` checker."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(
    0,
    str(
        Path(__file__).resolve().parent.parent
        / "src"
        / "claude_all"
        / "skills"
        / "generic"
        / "prek"
        / "checkers"
    ),
)

from hooks_installed import main

SHIM = "#!/bin/sh\n# File generated by prek: https://github.com/j178/prek\nexec prek\n"


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)
    # pin hooksPath in local config so the host's global config cannot leak in
    subprocess.run(
        ["git", "-C", str(tmp_path), "config", "core.hooksPath", "custom-hooks"], check=True
    )
    (tmp_path / "custom-hooks").mkdir()
    return tmp_path


def install(repo: Path, hook_type: str) -> None:
    shim = repo / "custom-hooks" / hook_type
    shim.write_text(SHIM)
    shim.chmod(0o755)


def test_missing_stage_shim_bites(repo: Path, capsys: pytest.CaptureFixture[str]) -> None:
    (repo / "prek.toml").write_text('default_install_hook_types = ["pre-commit", "pre-push"]\n')
    install(repo, "pre-commit")
    # a shim in the default .git/hooks dir must not count: core.hooksPath wins
    (repo / ".git" / "hooks" / "pre-push").write_text(SHIM)

    assert main(["--root", str(repo)]) == 1
    out = capsys.readouterr().out
    assert "custom-hooks/pre-push: no shim installed" in out
    assert "pre-commit:" not in out


def test_non_executable_shim_bites(repo: Path) -> None:
    (repo / "prek.toml").write_text('default_install_hook_types = ["pre-commit"]\n')
    (repo / "custom-hooks" / "pre-commit").write_text(SHIM)

    assert main(["--root", str(repo)]) == 1


def test_all_stages_installed_is_clean(repo: Path) -> None:
    (repo / "prek.toml").write_text('default_install_hook_types = ["pre-commit", "commit-msg"]\n')
    install(repo, "pre-commit")
    install(repo, "commit-msg")

    assert main(["--root", str(repo)]) == 0


def test_pre_commit_yaml_block_list(repo: Path) -> None:
    (repo / ".pre-commit-config.yaml").write_text(
        "default_install_hook_types:\n  - pre-commit\n  - pre-push\nrepos: []\n"
    )
    install(repo, "pre-commit")

    assert main(["--root", str(repo)]) == 1
    install(repo, "pre-push")
    assert main(["--root", str(repo)]) == 0


def test_zero_declared_stages_fails_closed(repo: Path) -> None:
    (repo / "prek.toml").write_text("default_install_hook_types = []\n")

    assert main(["--root", str(repo)]) == 2


def test_unknown_stage_fails_closed(repo: Path) -> None:
    install(repo, "pre-commit")
    (repo / "prek.toml").write_text('default_install_hook_types = ["pre-commit", "pre-deploy"]\n')

    assert main(["--root", str(repo)]) == 2


def test_not_a_git_repo_fails_closed(tmp_path: Path) -> None:
    (tmp_path / "prek.toml").write_text('default_install_hook_types = ["pre-commit"]\n')

    assert main(["--root", str(tmp_path)]) == 2


def test_toml_11_tables_after_preamble_are_tolerated(repo: Path) -> None:
    (repo / "prek.toml").write_text(
        'default_install_hook_types = ["pre-commit"]\n\n[[repos]]\nrepo = "local"\n'
        'hooks = [\n  {\n    id = "x",\n    entry = "true"\n  },\n]\n'
    )
    install(repo, "pre-commit")

    assert main(["--root", str(repo)]) == 0
