#!/usr/bin/env python3
"""Checker: every stage in `default_install_hook_types` has an installed git hook shim.

WHY: a hook scoped to a stage whose shim was never installed cannot run at all — it is prose.
Reads prek.toml (or .pre-commit-config.yaml) and inspects the hooks dir git really uses
(`git rev-parse --git-path hooks`, which honors `core.hooksPath` incl. per-worktree config).
"""

import argparse
import os
import re
import subprocess  # nosec B404 — fixed argv list, no shell
import sys
import tomllib
from pathlib import Path

__all__ = [
    "KNOWN_GIT_HOOK_TYPES",
    "SHIM_MARKERS",
    "declared_hook_types",
    "git_hooks_dir",
    "main",
    "parse_yaml_hook_types",
    "shim_problem",
    "toplevel_preamble",
]

KNOWN_GIT_HOOK_TYPES = frozenset(
    {
        "commit-msg",
        "post-checkout",
        "post-commit",
        "post-merge",
        "post-rewrite",
        "pre-commit",
        "pre-merge-commit",
        "pre-push",
        "pre-rebase",
        "prepare-commit-msg",
    }
)
SHIM_MARKERS: tuple[str, ...] = ("File generated by prek", "File generated by pre-commit")
KEY = "default_install_hook_types"


def parse_yaml_hook_types(text: str) -> list[str]:
    lines = text.splitlines()
    for index, line in enumerate(lines):
        match = re.match(rf"^{KEY}\s*:\s*(.*?)\s*(?:#.*)?$", line)
        if not match:
            continue
        inline = match.group(1)
        if inline.startswith("["):
            return [v.strip().strip("'\"") for v in inline.strip("[]").split(",") if v.strip()]
        items: list[str] = []
        for item in lines[index + 1 :]:
            entry = re.match(r"^\s+-\s*([^#\s]+)", item)
            if not entry:
                break
            items.append(entry.group(1).strip("'\""))
        return items
    return []


def toplevel_preamble(text: str) -> str:
    lines = text.splitlines(keepends=True)
    end = next((i for i, line in enumerate(lines) if line.startswith("[")), len(lines))
    return "".join(lines[:end])


def declared_hook_types(config: Path) -> list[str] | str:
    try:
        text = config.read_text(encoding="utf-8")
        if config.suffix == ".toml":
            # parse only top-level keys: tables may use TOML 1.1 syntax py3.12 cannot read
            raw = tomllib.loads(toplevel_preamble(text)).get(KEY)
            declared = [str(v) for v in raw] if isinstance(raw, list) else []
        else:
            declared = parse_yaml_hook_types(text)
    except (OSError, UnicodeDecodeError, tomllib.TOMLDecodeError) as exc:
        return f"{config}: could not be read: {exc}"
    if not declared:
        return f"{config}: declares no non-empty `{KEY}` — nothing to verify"
    unknown = sorted(set(declared) - KNOWN_GIT_HOOK_TYPES)
    if unknown:
        return f"{config}: unknown hook type(s) {', '.join(unknown)} — refusing to skip them"
    return declared


def git_hooks_dir(root: Path) -> Path | str:
    results: list[str] = []
    for query in (["--show-toplevel"], ["--git-path", "hooks"]):
        try:
            proc = subprocess.run(  # nosec B603 B607 — fixed argv list
                ["git", "-C", str(root), "rev-parse", *query],
                capture_output=True,
                text=True,
                check=False,
            )
        except OSError as exc:
            return f"could not run git: {exc}"
        if proc.returncode != 0 or not proc.stdout.strip():
            return f"git rev-parse {' '.join(query)} failed: {proc.stderr.strip()}"
        results.append(proc.stdout.strip())
    return (Path(results[0]) / results[1]).resolve()


def shim_problem(hooks_dir: Path, hook_type: str) -> str | None:
    shim = hooks_dir / hook_type
    if not shim.is_file():
        return "no shim installed"
    if not os.access(shim, os.X_OK):
        return "shim is not executable — git will not run it"
    try:
        body = shim.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        return f"shim could not be read: {exc}"
    if not any(marker in body for marker in SHIM_MARKERS):
        return "file exists but is not a prek/pre-commit shim"
    legacy = hooks_dir / f"{hook_type}.legacy"
    if legacy.is_file() and os.access(legacy, os.X_OK):
        return f"stale executable {legacy.name} also runs — remove it and reinstall"
    return None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Verify declared git hook stages are installed.")
    parser.add_argument("--root", type=Path, default=Path(), help="repo root (default: cwd)")
    parser.add_argument("--config", type=Path, help="prek.toml or .pre-commit-config.yaml")
    args = parser.parse_args(argv)
    hooks_dir = git_hooks_dir(args.root)
    if isinstance(hooks_dir, str):
        print(f"CANNOT CHECK: {hooks_dir}", file=sys.stderr)
        return 2
    candidates = (
        [args.config]
        if args.config
        else [args.root / "prek.toml", args.root / ".pre-commit-config.yaml"]
    )
    config = next((c for c in candidates if c.is_file()), None)
    if config is None:
        print(f"CANNOT CHECK: no hook config found among {candidates}", file=sys.stderr)
        return 2
    declared = declared_hook_types(config)
    if isinstance(declared, str):
        print("scanned=0 declared hook type(s)", file=sys.stderr)
        print(f"CANNOT CHECK: {declared}", file=sys.stderr)
        return 2
    print(f"scanned={len(declared)} declared hook type(s)", file=sys.stderr)
    print(f"hooks dir inspected: {hooks_dir}", file=sys.stderr)
    problems = [(t, p) for t in declared if (p := shim_problem(hooks_dir, t))]
    for hook_type, problem in problems:
        print(f"{hooks_dir / hook_type}: {problem} (fix: `prek install`)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
