"""claude-all as a prek/pre-commit hook repo.

Each skill declares the checkers it ships in its claude-all.json `prek_hooks`. From those
specs this module renders `.pre-commit-hooks.yaml`, runs a hook (`claude-all-check <id>`),
and writes a managed block into a project's prek.toml / .pre-commit-config.yaml.
"""

from __future__ import annotations

import argparse
import difflib
import json  # guard:allow — zero-dependency package (hook envs install it bare), like cli.py
import re
import shlex
import subprocess
import sys
import tomllib
from collections.abc import Mapping, Sequence
from importlib.metadata import metadata, version
from pathlib import Path
from typing import NamedTuple

from claude_all.cli import REPO_ROOT, STATE_FILE

__all__ = [
    "STATE_FILE",
    "HookSpec",
    "InstallPlan",
    "apply_plan",
    "cmd_install_hooks",
    "detect_layout",
    "load_hook_specs",
    "main",
    "plan_install",
    "render_manifest",
    "run_check",
]

START = "# >>> claude-all hooks (managed by `claude-all --install-hooks`; don't edit) >>>"
END = "# <<< claude-all hooks <<<"
PLACEHOLDER = re.compile(r"\{(\w+)\}")
BASELINE_GATE = REPO_ROOT / "skills" / "generic" / "regression-gates" / "baseline_gate.py"


class HookSpec(NamedTuple):
    id: str
    name: str
    description: str
    skill: str
    script_path: Path
    args: tuple[str, ...]
    pass_filenames: bool
    types: tuple[str, ...]
    default: bool
    exit_zero_flag: str | None
    stdout_findings: bool


class InstallPlan(NamedTuple):
    target: Path
    old_text: str
    new_text: str
    hooks: list[tuple[str, list[str]]]
    skipped: Mapping[str, str]
    optional: list[str]


def load_hook_specs(root: Path = REPO_ROOT) -> list[HookSpec]:
    specs: list[HookSpec] = []
    for manifest in sorted((root / "skills").glob("*/*/claude-all.json")):
        config = json.loads(manifest.read_text())
        for raw in config.get("prek_hooks", []):
            specs.append(
                HookSpec(
                    id=raw["id"],
                    name=raw["name"],
                    description=raw["description"],
                    skill=f"skills/{manifest.parent.name}",
                    script_path=manifest.parent / raw["script"],
                    args=tuple(raw.get("args", [])),
                    pass_filenames=raw.get("pass_filenames", False),
                    types=tuple(raw.get("types", ["python"])),
                    default=raw.get("default", True),
                    exit_zero_flag=raw.get("exit_zero_flag"),
                    stdout_findings=raw.get("stdout_findings", False),
                )
            )
    return sorted(specs, key=lambda spec: spec.id)


def render_manifest(specs: Sequence[HookSpec]) -> str:
    lines = ["# Generated by `python -m claude_all.prek_hooks --manifest`; do not edit.", ""]
    for spec in specs:
        lines += [
            f"- id: {spec.id}",
            f"  name: {json.dumps(spec.name, ensure_ascii=False)}",
            f"  description: {json.dumps(spec.description, ensure_ascii=False)}",
            f"  entry: claude-all-check {spec.id}",
            "  language: python",
            f"  types: {json.dumps(list(spec.types))}",
            f"  pass_filenames: {str(spec.pass_filenames).lower()}",
            "",
        ]
    return "\n".join(lines)


def run_check(argv: Sequence[str] | None = None) -> int:
    """Hook entry point; argv is `<id> [--baseline FILE] [args...]` (default: sys.argv)."""
    args = list(sys.argv[1:] if argv is None else argv)
    if not args:
        print("usage: claude-all-check <hook-id> [--baseline FILE] [args...]", file=sys.stderr)
        return 2
    spec = {spec.id: spec for spec in load_hook_specs()}.get(args[0])
    if spec is None:
        print(f"claude-all-check: unknown hook id {args[0]!r}", file=sys.stderr)
        return 2
    rest = args[1:]
    command = [sys.executable, str(spec.script_path)]
    if rest[:1] == ["--baseline"] and len(rest) >= 2:
        if spec.exit_zero_flag is None and not spec.stdout_findings:
            print(f"claude-all-check: {spec.id} does not support --baseline", file=sys.stderr)
            return 2
        gate = [sys.executable, str(BASELINE_GATE), "--baseline", rest[1], "--strip-lines"]
        rest = rest[2:]
        if rest[:1] == ["--update"]:
            gate.append("--update")
            rest = rest[1:]
        # Record a machine-independent identity: the interpreter/script paths differ per env.
        gate += ["--seed-label", shlex.join(["claude-all-check", spec.id, *rest])]
        if spec.exit_zero_flag:
            rest.append(spec.exit_zero_flag)
        command = [*gate, "--", *command]
        return subprocess.run([*command, *rest], check=False).returncode
    if not spec.stdout_findings:
        return subprocess.run([*command, *rest], check=False).returncode
    # Baseline-native checkers print findings and exit 0; with no baseline, any finding fails.
    proc = subprocess.run([*command, *rest], capture_output=True, text=True, check=False)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    return proc.returncode or (1 if proc.stdout.strip() else 0)


def detect_layout(root: Path) -> dict[str, str]:
    layout: dict[str, str] = {}
    if (root / "src").is_dir():
        layout["src"] = "src"
    package = project_package(root)
    if package is not None:
        layout["package"] = package
        layout.setdefault("src", package)
    # A hook over a directory with nothing to scan exits 2 (fail closed): only offer real ones.
    if has_files(root / "tests", "*.py"):
        layout["tests"] = "tests"
        layout["unit_tests"] = (
            "tests/unit" if has_files(root / "tests" / "unit", "*.py") else "tests"
        )
        if has_files(root / "tests" / "e2e", "*.py"):
            layout["e2e_tests"] = "tests/e2e"
    for candidate in ("infra", "terraform", "iac"):
        if has_files(root / candidate, "*.tf"):
            layout["infra"] = candidate
            break
    for candidate in ("alembic/versions", "migrations/versions", "db/migrations/versions"):
        if has_files(root / candidate, "*.py"):
            layout["migrations"] = candidate
            break
    return layout


def has_files(directory: Path, pattern: str) -> bool:
    return directory.is_dir() and next(directory.rglob(pattern), None) is not None


def project_package(root: Path) -> str | None:
    pyproject = root / "pyproject.toml"
    if pyproject.is_file():
        name = tomllib.loads(pyproject.read_text()).get("project", {}).get("name")
        if name:
            candidate = re.sub(r"[-.]", "_", name).lower()
            if (root / "src" / candidate).is_dir() or (root / candidate).is_dir():
                return candidate
    src = root / "src"
    if src.is_dir():
        for child in sorted(src.iterdir()):
            if (child / "__init__.py").is_file():
                return child.name
    return None


def resolve_args(spec: HookSpec, layout: Mapping[str, str]) -> list[str] | str:
    """Fill spec args from layout; return the first missing placeholder name instead."""
    resolved: list[str] = []
    for arg in spec.args:
        missing = [key for key in PLACEHOLDER.findall(arg) if key not in layout]
        if missing:
            return missing[0]
        resolved.append(PLACEHOLDER.sub(lambda m: layout[m.group(1)], arg))
    return resolved


def installed_skills(state: Mapping[str, object]) -> set[str]:
    installs = state.get("installs", {})
    if not isinstance(installs, dict):
        return set()
    return {key for key in installs if key.startswith("skills/")}


def plan_install(
    root: Path, state: Mapping[str, object], rev: str, only: Sequence[str] = ()
) -> InstallPlan:
    specs = load_hook_specs()
    unknown = sorted(set(only) - {spec.id for spec in specs})
    if unknown:
        raise ValueError(f"unknown hook id(s): {', '.join(unknown)}")
    skills = installed_skills(state)
    layout = detect_layout(root)
    hooks: list[tuple[str, list[str]]] = []
    skipped: dict[str, str] = {}
    optional: list[str] = []
    for spec in specs:
        if spec.skill not in skills:
            continue
        if not spec.default and spec.id not in only:
            optional.append(spec.id)
            continue
        args = resolve_args(spec, layout)
        if isinstance(args, str):
            skipped[spec.id] = f"cannot detect {{{args}}} in this project"
            continue
        hooks.append((spec.id, args))
    target = config_target(root)
    old_text = target.read_text() if target.exists() else ""
    repo_url = hook_repo_url()
    if target.suffix == ".toml":
        new_text = replace_block(old_text, toml_block(repo_url, rev, hooks))
        ensure_valid_toml(old_text, new_text, target)
    else:
        new_text = insert_yaml_block(old_text, repo_url, rev, hooks)
    return InstallPlan(target, old_text, new_text, hooks, skipped, optional)


def hook_repo_url() -> str:
    for entry in metadata("claude-all").get_all("Project-URL") or []:
        label, _, url = entry.partition(", ")
        if label.lower() == "repository":
            return url
    raise RuntimeError("claude-all package metadata has no Repository URL")


def config_target(root: Path) -> Path:
    for name in ("prek.toml", ".pre-commit-config.yaml", ".pre-commit-config.yml"):
        if (root / name).is_file():
            return root / name
    return root / "prek.toml"


def toml_block(repo_url: str, rev: str, hooks: Sequence[tuple[str, list[str]]]) -> str:
    lines = [START, "[[repos]]", f"repo = {json.dumps(repo_url)}", f"rev = {json.dumps(rev)}"]
    lines.append("hooks = [")
    for hook_id, args in hooks:
        entry = f'id = "{hook_id}"' + (f", args = {json.dumps(args)}" if args else "")
        lines.append(f"  {{ {entry} }},")
    lines += ["]", END]
    return "\n".join(lines)


def ensure_valid_toml(old_text: str, new_text: str, target: Path) -> None:
    try:
        tomllib.loads(old_text)
    except tomllib.TOMLDecodeError:
        return  # a dialect tomllib can't read (e.g. TOML 1.1): nothing to compare against
    try:
        tomllib.loads(new_text)
    except tomllib.TOMLDecodeError as exc:
        raise ValueError(
            f"the managed block would not be valid TOML in {target.name} ({exc}); if it "
            "declares `repos = [...]` inline, switch it to `[[repos]]` tables first"
        ) from exc


def marker_span(text: str, start: str, end: str) -> tuple[int, int] | None:
    """Return the (start, end) offsets of the one managed block in text, or None."""
    starts, ends = text.count(start), text.count(end)
    if (starts, ends) == (0, 0):
        return None
    begin, finish = text.find(start), text.find(end)
    if (starts, ends) != (1, 1) or finish < begin:
        raise ValueError(
            "claude-all hooks markers are missing, duplicated or out of order; fix them by "
            "hand (keep exactly one start and one end marker) and re-run"
        )
    return begin, finish + len(end)


def replace_block(text: str, block: str) -> str:
    span = marker_span(text, START, END)
    if span is not None:
        return text[: span[0]] + block + text[span[1] :]
    prefix = text.rstrip("\n")
    return f"{prefix}\n\n{block}\n" if prefix else f"{block}\n"


def insert_yaml_block(
    text: str, repo_url: str, rev: str, hooks: Sequence[tuple[str, list[str]]]
) -> str:
    lines = text.splitlines(keepends=True)
    repos_re = re.compile(r"^repos:\s*(\[\s*\])?\s*(#.*)?$")
    repos_at = next((i for i, line in enumerate(lines) if repos_re.match(line)), None)
    if repos_at is None:
        raise ValueError("no top-level `repos:` key in the pre-commit config")
    match = repos_re.match(lines[repos_at])
    if match and match.group(1):  # `repos: []` -> block list, keeping any trailing comment
        lines[repos_at] = "repos:" + (f"  {match.group(2)}" if match.group(2) else "") + "\n"
    indent = "  "
    for line in lines[repos_at + 1 :]:
        if re.match(r"^\S", line) and not line.startswith("#"):
            break  # next top-level key: repos had no items
        match = re.match(r"^(\s*)- ", line)
        if match:
            indent = match.group(1)
            break
    block = [f"{indent}{START}", f"{indent}- repo: {repo_url}", f"{indent}  rev: {rev}"]
    block.append(f"{indent}  hooks:")
    for hook_id, args in hooks:
        block.append(f"{indent}    - id: {hook_id}")
        if args:
            block.append(f"{indent}      args: {json.dumps(args)}")
    block.append(f"{indent}{END}")
    body = "".join(lines)
    span = marker_span(body, START, END)
    if span is not None:
        line_start = body.rfind("\n", 0, span[0]) + 1
        line_end = body.find("\n", span[1])
        line_end = len(body) if line_end == -1 else line_end + 1
        return body[:line_start] + "".join(f"{line}\n" for line in block) + body[line_end:]
    rendered = "".join(f"{line}\n" for line in block)
    return "".join(lines[: repos_at + 1]) + rendered + "".join(lines[repos_at + 1 :])


def apply_plan(plan: InstallPlan) -> None:
    plan.target.write_text(plan.new_text)


def project_root() -> Path:
    proc = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=False
    )
    return Path(proc.stdout.strip()) if proc.returncode == 0 else Path.cwd()


def cmd_install_hooks(
    *, assume_yes: bool, dry_run: bool, rev: str | None = None, only: Sequence[str] = ()
) -> int:
    root = project_root()
    try:
        state = json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else {}
        plan = plan_install(root, state, rev or f"v{version('claude-all')}", only)
    except (ValueError, OSError) as exc:  # JSON/TOML decode errors are ValueErrors
        print(f"claude-all --install-hooks: {exc}", file=sys.stderr)
        return 2
    if not plan.hooks:
        print("No claude-all hooks to wire: install a skill that ships checkers first.")
        return 0
    print(f"Hooks for {root} → {plan.target.name}:")
    for hook_id, args in plan.hooks:
        print(f"  + {hook_id} {' '.join(args)}".rstrip())
    for hook_id, reason in plan.skipped.items():
        print(f"  ! skipped {hook_id}: {reason}")
    if plan.optional:
        print(f"  available, not enabled (add with --hook <id>): {', '.join(plan.optional)}")
    if plan.new_text == plan.old_text:
        print(f"{plan.target.name} is already current.")
        return 0
    sys.stdout.writelines(
        difflib.unified_diff(
            plan.old_text.splitlines(keepends=True),
            plan.new_text.splitlines(keepends=True),
            fromfile=f"a/{plan.target.name}",
            tofile=f"b/{plan.target.name}",
        )
    )
    if dry_run:
        return 0
    if not assume_yes:
        if not sys.stdin.isatty():
            print("Refusing to write without a terminal; re-run with --yes.", file=sys.stderr)
            return 1
        if input(f"Write {plan.target.name}? [y/N] ").strip().lower() not in {"y", "yes"}:
            print("Aborted.")
            return 1
    apply_plan(plan)
    print(f"Wrote {plan.target}. Next: `prek install` then `prek run --all-files`.")
    print('Existing debt? Ratchet a hook: args = ["--baseline", "<gate>_baseline.txt", ...].')
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m claude_all.prek_hooks")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--manifest", action="store_true", help="print .pre-commit-hooks.yaml")
    group.add_argument("--run", nargs=argparse.REMAINDER, help="run a hook: --run <id> [args]")
    args = parser.parse_args(argv)
    if args.manifest:
        sys.stdout.write(render_manifest(load_hook_specs()))
        return 0
    return run_check(args.run)


if __name__ == "__main__":
    raise SystemExit(main())
